export const THAINOW_USER_STORRAGE_OBJ = "thainow.user";

export const ERROR = "ERROR";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const ERROR_TYPE = "ERROR_STATUS";

export const COMPANY_INDUSTRY_LIST = [
	"Aquarium & Pet",
	"Attorney",
	"Auto Service",
	"Bank",
	"Bar",
	"Bodyshop",
	"Book Store",
	"Bookkeeping",
	"Boxing",
	"Car Dealer",
	"Car Towing",
	"Chiropractic",
	"Clothing",
	"Community Service",
	"Construction",
	"Consulate",
	"Consultant",
	"Cosmetic",
	"Credit Card Services",
	"Dance",
	"Dentist",
	"Doctor Clinic",
	"Drink and Dessert",
	"DVD, CD, Games",
	"Education",
	"Elderly Care",
	"Embassy",
	"Factory",
	"Flower",
	"Fusion Restaurant",
	"Gift Shop",
	"Hair Salon",
	"Handyman",
	"Insurance",
	"Japanese Restaurant",
	"Jewelry and Watch",
	"Market",
	"Mobile",
	"Money Transfer",
	"Nail",
	"Newspaper",
	"Notary Public",
	"Optical",
	"Others",
	"Painter",
	"Personal Trainer",
	"Printing",
	"Real Estate",
	"School",
	"Shipping",
	"Tailor",
	"Tax",
	"Taxi",
	"Television",
	"Thai Church",
	"Thai Massage",
	"Thai Restaurant",
	"Thai Temple",
	"Trader",
	"Travel Agency",
	"Vegan Restaurant",
];

export const COMPANY_POSTION_LIST = ["Owner", "Director", "Manager", "Staff"];
