// error
export const DISPATCH_ERROR = "DISPATCH_ERROR";

export const DISPATCH_SIGNUP_CLASSIC_INFO = "DISPATCH_SIGNUP_CLASSIC_INFO";
export const DISPATCH_PATCH_SIGNUP_BUSINESS_INFO =
	"DISPATCH_PATCH_SIGNUP_BUSINESS_INFO";
