// error
export const DISPATCH_ERROR = "DISPATCH_ERROR";

// store object
export const DISPATCH_PATCH_STORE_ROOT_OBJ_INFO =
	"DISPATCH_PATCH_STORE_ROOT_OBJ_INFO";

// user
export const DISPATCH_PATCH_SIGNUP_USER_INFO =
	"DISPATCH_PATCH_SIGNUP_USER_INFO";

// user
export const DISPATCH_PATCH_SIGNIN_USER_INFO =
	"DISPATCH_PATCH_SIGNIN_USER_INFO";

// business
export const DISPATCH_PATCH_SIGNUP_COMPANY_INFO =
	"DISPATCH_PATCH_SIGNUP_COMPANY_INFO";

// search
export const DISPATCH_PATCH_SEARCH_INFO = "DISPATCH_PATCH_SEARCH_INFO";
