// error
export const DISPATCH_ERROR = "DISPATCH_ERROR";

// store object
export const DISPATCH_PATCH_STORE_ROOT_OBJ_INFO =
	"DISPATCH_PATCH_STORE_ROOT_OBJ_INFO";

// user object
export const DISPATCH_PATCH_USER_OBJ_INFO = "DISPATCH_PATCH_USER_OBJ_INFO";

// sign up user
export const DISPATCH_PATCH_SIGNUP_USER_INFO =
	"DISPATCH_PATCH_SIGNUP_USER_INFO";

// sign up business
export const DISPATCH_PATCH_SIGNUP_COMPANY_INFO =
	"DISPATCH_PATCH_SIGNUP_COMPANY_INFO";

// sign in user
export const DISPATCH_PATCH_SIGNIN_USER_INFO =
	"DISPATCH_PATCH_SIGNIN_USER_INFO";

// profile
export const DISPATCH_PATCH_PROFILE_INFO = "DISPATCH_PATCH_PROFILE_INFO";

// search
export const DISPATCH_PATCH_SEARCH_INFO = "DISPATCH_PATCH_SEARCH_INFO";

// off canvas
export const DISPATCH_PATCH_OFF_CANVAS_INFO = "DISPATCH_PATCH_OFF_CANVAS_INFO";
